Replaces readdir_r() for readdir()
Function readdir_r is being deprecated, which causes ltrace to fail to
build, using  with the following message:

	proc.c: In function ‘process_tasks’:
	proc.c:247:3: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
	   if (readdir_r(d, &entry, &result) != 0) {
	        ^~~~~~~~

This patch just replaces readdir_r() for readdir(). No changes is
expected.